## 1. csv, xls을 웹주소와 로컬 파일로 각각 읽어서 데이터프레임 작성

In [2]:
# 웹에서 raw 파일로 다운하여 가져오기

import pandas as pd

# 데이터 로드
file_path = "C:/AI/2week/mobile.csv"

# CSV 파일 불러오기
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [3]:
# 웹에서 url주소로 가져오기

import pandas as pd

# GitHub의 Raw CSV 파일 URL
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/mobile.csv"

# CSV 파일을 데이터프레임으로 불러오기
df = pd.read_csv(url)

# 데이터프레임 확인
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [4]:
# 웹에서 raw 파일로 다운하여 가져오기(excel)

import pandas as pd

# 파일 경로 지정
file_path = "C:/AI/2week/combined_dataset-1.xlsx"

# 엑셀 파일 불러오기
df = pd.read_excel(file_path, engine='openpyxl')

# 데이터 확인
df.head()

Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0     1           2   Female         45         152          63   
1     1           2   Female         45         152          63   
2     1           2   Female         45         152          63   
3     2           3   Female         50         157          50   
4     2           3   Female         50         157          50   

   Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                            161                              89   
1                            161                              89   
2                            161                              89   
3                            160                              93   
4                            160                              93   

   Heart Rate(b/m)  BMI(kg/m^2)  ...  2091  2092  2093  2094  2095  2096  \
0               97    27.268006  ...  1766  1766  1766  1833  1833  1827   
1               97    27.268006  ...  1985  1985  2026  2026  2026  1977   
2               97    27.268006  ...  1942  1900  1900  1938  1938  1938   
3               76    20.284799  ...  2073  2072  2072  2072  2051  2051   
4               76    20.284799  ...  2021  2010  2010  2010  2001  2001   

   2097  2098  2099  2100  
0  1827  1827  1754  1754  
1  1977  1997  1997  1997  
2  1924  1924  1929  1929  
3  2036  2036  2036  2045  
4  2003  2003  2003  1989  

[5 rows x 2114 columns]

In [5]:
# 웹에서 url 주소로 가져오기(excel)

import pandas as pd

# GitHub Raw 엑셀 파일 URL
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/combined_dataset-1.xlsx"

# 엑셀 파일 불러오기
df = pd.read_excel(url, engine='openpyxl')  # openpyxl 엔진 사용

# 데이터 확인
df.head()

Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0     1           2   Female         45         152          63   
1     1           2   Female         45         152          63   
2     1           2   Female         45         152          63   
3     2           3   Female         50         157          50   
4     2           3   Female         50         157          50   

   Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                            161                              89   
1                            161                              89   
2                            161                              89   
3                            160                              93   
4                            160                              93   

   Heart Rate(b/m)  BMI(kg/m^2)  ...  2091  2092  2093  2094  2095  2096  \
0               97    27.268006  ...  1766  1766  1766  1833  1833  1827   
1               97    27.268006  ...  1985  1985  2026  2026  2026  1977   
2               97    27.268006  ...  1942  1900  1900  1938  1938  1938   
3               76    20.284799  ...  2073  2072  2072  2072  2051  2051   
4               76    20.284799  ...  2021  2010  2010  2010  2001  2001   

   2097  2098  2099  2100  
0  1827  1827  1754  1754  
1  1977  1997  1997  1997  
2  1924  1924  1929  1929  
3  2036  2036  2036  2045  
4  2003  2003  2003  1989  

[5 rows x 2114 columns]

## 2. KNN 알고리즘 적용

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [8]:
# GitHub의 Raw CSV 파일 URL
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/mobile.csv"

# CSV 파일을 데이터프레임으로 불러오기
df = pd.read_csv(url)

# 데이터프레임 확인
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [9]:
# 입력 데이터(X)와 정답(y) 분리
X = df.iloc[:, :-1].values  # 마지막 열을 제외한 데이터 (특성)
y = df.iloc[:, -1].values   # 마지막 열

# 훈련 데이터와 테스트 데이터 나누기 (8:2 비율)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# KNN 모델 생성 & 학습
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# 예측 및 평가
y_pred_knn = knn.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print(f"KNN 정확도: {accuracy_knn * 100:.2f}%")

KNN 정확도: 94.25%


## 3. 예측한값과 정답 두개 비교

In [11]:
# 예측 결과를 DataFrame으로 정리
comparison_df = pd.DataFrame({
    "실제 정답 (y_test)": y_test,
    "예측값 (y_pred)": y_pred_knn
})

# 비교 테이블 출력
comparison_df.head(10)

실제 정답 (y_test)  예측값 (y_pred)
0               0             0
1               2             2
2               1             1
3               3             3
4               1             1
5               1             1
6               2             2
7               0             0
8               3             3
9               1             1

## diabetes.csv 파일 사용하기

In [13]:
# GitHub에서 CSV 파일 불러오기
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/diabetes.csv"
df = pd.read_csv(url)

# 데이터 확인
print(df.head())
print(df.info())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768

In [14]:
# 입력 데이터(X)와 정답(y) 분리
X = df.iloc[:, :-1].values  # 마지막 열을 제외한 데이터 (특성)
y = df.iloc[:, -1].values   # 마지막 열 (당뇨병 여부)

# 훈련 데이터와 테스트 데이터 나누기 (8:2 비율)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### DT 모델

In [16]:
# 결정 트리 모델 생성 & 학습
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

# 예측 및 평가
y_pred_dt = dt.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree 정확도: {accuracy_dt * 100:.2f}%")

Decision Tree 정확도: 77.27%


### RF 모델

In [18]:
# 랜덤 포레스트 모델 생성 & 학습
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

# 예측 및 평가
y_pred_rf = rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest 정확도: {accuracy_rf * 100:.2f}%")

Random Forest 정확도: 75.32%


### SVM 모델

In [20]:
# SVM 모델 생성 & 학습
svm = SVC()
svm.fit(X_train, y_train)

# 예측 및 평가
y_pred_svm = svm.predict(X_test)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM 정확도: {accuracy_svm * 100:.2f}%")

SVM 정확도: 76.62%


### LR 모델

In [22]:
# 로지스틱 회귀 모델 생성 & 학습
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

# 예측 및 평가
y_pred_lr = lr.predict(X_test)
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print(f"Logistic Regression 정확도: {accuracy_lr * 100:.2f}%")

Logistic Regression 정확도: 74.68%


### KNN 모델

In [24]:
# KNN 모델 생성 & 학습
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# 예측 및 평가
y_pred_knn = knn.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print(f"KNN 정확도: {accuracy_knn * 100:.2f}%")

KNN 정확도: 66.23%


## 타이타닉 데이터

In [26]:
import pandas as pd

# 파일 불러오기
file_path = "C:/AI/2week/titanic.csv"
df = pd.read_csv(file_path)

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
# 1. name, ticket, cabin, embarked 컬럼 삭제
df = df.drop(columns=['Name', 'Ticket', 'Cabin', 'Embarked'])

# 2. age를 숫자(float)로 변환 (오류 방지)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')  # 숫자로 변환, 변환 불가능한 값은 NaN 처리

# 3. age의 평균값 계산 후 결측치 채우기
age_mean = round(df['Age'].mean())
df['Age'] = age_mean

df.head()

PassengerId  Survived  Pclass     Sex  Age  SibSp  Parch     Fare
0            1         0       3    male   30      1      0   7.2500
1            2         1       1  female   30      1      0  71.2833
2            3         1       3  female   30      0      0   7.9250
3            4         1       1  female   30      1      0  53.1000
4            5         0       3    male   30      0      0   8.0500

In [28]:
from sklearn.preprocessing import LabelEncoder

# sex 컬럼을 숫자로 변환 (male=0, female=1)
encoder = LabelEncoder()
df['Sex'] = encoder.fit_transform(df['Sex'])

# 변환 후 데이터 확인
print(df['Sex'].value_counts())

Sex
1    577
0    314
Name: count, dtype: int64


In [29]:
print(df['Survived'].value_counts())

Survived
0    549
1    342
Name: count, dtype: int64


In [30]:
from sklearn.model_selection import train_test_split

# 입력 데이터(X)와 정답(y) 분리
X = df.drop(columns=['Survived']).values
y = df['Survived'].values  # 정답 데이터

# 80% 훈련 / 20% 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"훈련 데이터 크기: {X_train.shape}, 테스트 데이터 크기: {X_test.shape}")

훈련 데이터 크기: (712, 7), 테스트 데이터 크기: (179, 7)


### RF 모델

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# 모델 학습
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

# 예측
y_pred_rf = rf.predict(X_test)

# 평가
accuracy_rf = accuracy_score(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)

print(f"Random Forest 정확도: {accuracy_rf * 100:.2f}%")
print("Confusion Matrix:\n", conf_matrix_rf)

Random Forest 정확도: 80.45%
Confusion Matrix:
 [[91 14]
 [21 53]]


### DT 모델

In [34]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)

print(f"Decision Tree 정확도: {accuracy_dt * 100:.2f}%")
print("Confusion Matrix:\n", conf_matrix_dt)

Decision Tree 정확도: 69.83%
Confusion Matrix:
 [[81 24]
 [30 44]]


### LR 모델

In [36]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)

print(f"Logistic Regression 정확도: {accuracy_lr * 100:.2f}%")
print("Confusion Matrix:\n", conf_matrix_lr)

Logistic Regression 정확도: 78.21%
Confusion Matrix:
 [[89 16]
 [23 51]]


### KNN 모델

In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)

print(f"KNN 정확도: {accuracy_knn * 100:.2f}%")
print("Confusion Matrix:\n", conf_matrix_knn)

KNN 정확도: 67.60%
Confusion Matrix:
 [[90 15]
 [43 31]]


### SVM 모델

In [40]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

print(f"SVM 정확도: {accuracy_svm * 100:.2f}%")
print("Confusion Matrix:\n", conf_matrix_svm)

SVM 정확도: 59.78%
Confusion Matrix:
 [[103   2]
 [ 70   4]]


### 정확도 비교

In [42]:
accuracy_results = {
    "Random Forest": accuracy_rf,
    "Decision Tree": accuracy_dt,
    "Logistic Regression": accuracy_lr,
    "KNN": accuracy_knn,
    "SVM": accuracy_svm
}

print("\n===== 모델별 정확도 비교 =====")
for model, acc in accuracy_results.items():
    print(f"{model}: {acc * 100:.2f}%")


===== 모델별 정확도 비교 =====
Random Forest: 80.45%
Decision Tree: 69.83%
Logistic Regression: 78.21%
KNN: 67.60%
SVM: 59.78%


In [43]:
best_model = max(accuracy_results, key=accuracy_results.get)
print(f"\n최고 성능 모델: {best_model} (정확도: {accuracy_results[best_model] * 100:.2f}%)")


최고 성능 모델: Random Forest (정확도: 80.45%)
